import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "../styles/globals.css";
import "../styles/page.css";
import { AppProps } from "next/app";
import Footer from "src/components/Footer/Footer";

const source_code_pro = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--font'
})

export const metadata: Metadata = {
  title: "Cleiton Cabral",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <main className={source_code_pro.className}>
      <Component className='main' {...pageProps} />

      <Footer />
    </main>
  );
}

export default MyApp;