import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import './page.css'

const source_code_pro = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--font'
})

export const metadata: Metadata = {
  title: "Cleiton Cabral",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={source_code_pro.variable}>{children}</body>
    </html>
  );
}
